spring:
  application:
    name: schedule
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: dev
    url: jdbc:mysql://157.0.19.2:10208/schedule?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2b8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 157.0.19.2
    port: 10248


